# Generated by Django 4.1.7 on 2023-04-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_elevator_status_elevator_close_elevator_down_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
