# Generated by Django 4.1.7 on 2023-04-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_elevator_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='floor',
            field=models.IntegerField(default=0),
        ),
    ]
