# Generated by Django 4.1.7 on 2023-04-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_elevator_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='down',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='running',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='up',
        ),
        migrations.AddField(
            model_name='elevator',
            name='direction',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='elevator',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('running', 'running'), ('stop', 'stop')], default='idle', max_length=100),
        ),
    ]
