# Generated by Django 4.1.7 on 2023-04-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_elevator_down_remove_elevator_running_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='next_destination',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='status',
            field=models.CharField(choices=[('running', 'running'), ('stop', 'stop')], default='stop', max_length=100),
        ),
    ]
